# docker build -t rabbitmq:3.12.14-management-plugins -f Dockerfile.mq .
FROM rabbitmq:3.12.14-management
RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp